spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: true
          routes:
            - id: odm-auth
              uri: http://localhost:8090
              predicates:
                - Path= /auth/**,/test/**,
              filters:
                - JwtAuthenticationFilter
            - id: odm-finance
              uri: http://localhost:8091
              predicates:
                - Path= /api/produits/**,/api/payments/**,/api/pdf/**,/api/stripe/**
              filters:
                - JwtAuthenticationFilter
            - id: odm-payment
              uri: http://localhost:8082
              predicates:
                - Path= /api/v1/payment/**
              filters:
                - JwtAuthenticationFilter
    consul:
      enabled: false
      discovery:
        enabled: false
      config:
        enabled: false

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.server.adapter: DEBUG
    org.springframework.web.reactive: DEBUG
#JWT
jwt:
  secret: Emh/eYc9/h2cvrr1/i/+QsufTPEgtwi7sW9TxOnfs1g=
